cp .aliases ~/.aliases
cp .bash_profile ~/.bash_profile
cp .bash_prompt ~/.bash_prompt
cp .curlrc ~/.curlrc
cp .exports ~/.exports
cp .extra ~/.extra
cp .functions ~/.functions
cp .gitconfig ~/.gitconfig
#cp .gitignore_global ~/.gitignore_global
cp .hushlogin ~/.hushlogin
cp .inputrc ~/.inputrc
cp .path ~/.path
cp .screenrc ~/.screenrc
cp .wgetrc ~/.wgetrc